# Write your MySQL query statement below
SELECT NAME, IFNULL(SUM(R.DISTANCE),0) AS TRAVELLED_DISTANCE
FROM USERS U LEFT JOIN RIDES R ON U.ID = R.USER_ID
GROUP BY NAME, U.ID
ORDER BY TRAVELLED_DISTANCE DESC, U.NAME ASC;